#
# Dockerfile for h2o
#

FROM alpine
MAINTAINER Lars K.W. Gohlke <lkwg82@gmx.de>

RUN apk update \
    && apk add -U build-base \
               ca-certificates \
               cmake \
               docker \
               git \
               linux-headers \
               zlib-dev \
    && rm -rf /var/cache/apk/*
RUN git clone https://github.com/h2o/h2o.git h2o
WORKDIR /h2o

ADD build.sh /
ENTRYPOINT /build.sh
